apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-express-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: my-express-app
  template:
    metadata:
      labels:
        app: my-express-app
    spec:
      containers:
        - name: my-express-app
          image: muhohoweb/express-app:1.0.1
          ports:
            - containerPort: 3000 # Port your application listens on
