apiVersion: v1
kind: Service
metadata:
  name: my-express-app-service
spec:
  selector:
    app: my-express-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000 # Port your application listens on in the container
  type: NodePort # Change this if needed (NodePort, LoadBalancer, ClusterIP, etc.)
